import { nanoid } from "nanoid";

// export const clientResourcesGridColumn: any = {
//   url: "/group/getGridColumn",
//   columns: [
//     { field: "enabled", headerName: "فعال ", width: 150 },
//     { field: "description", headerName: "توصیف", width: 150 },
//   ],
// };

export const clientResourcesGridColumn: any = {
  url: "/group/getGridColumn",
  columns: [
    { field: "name", headerName: "نام ", width: 150 },
    { field: "lastname", headerName: "نام خانوادگی", width: 150 },
    { field: "gender", headerName: "جنسیت", width: 150 },
    { field: "itemType", headerName: "نوع", width: 150 },
    { field: "group", headerName: "گروه", width: 150 },
    { field: "checkbox", headerName: "چکباکس", width: 150 },
    { field: "startdate", headerName: "تاریخ شروع", width: 150 },
    { field: "actions", headerName: "عملیات", width: 150 },
  ],
};

export const clientResourcesData: any = {
  // pageSize: 5,
  // pageNumber: 1,
  total: 9,
  rows: [
    {
      id: nanoid(),
      name: "امنیت ۱",
      lastname: "امنیتی ",
      gender: "مرد",
      itemType: "نوع ۱",
      group: "گروه ۱",
      checkbox: "تایید شده",
      startdate: "1401-10-11",
      actions: ["delete", "edit", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۲",
      lastname: "امنیت ۲",
      gender: "زن",
      itemType: "نوع ۲",
      group: "گروه ۲",
      checkbox: "تایید شده",
      startdate: "1401-10-12",
      actions: ["delete", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۳",
      lastname: "امنیت ۳",
      gender: "مرد",
      itemType: "نوع ۳",
      group: "گروه ۳",
      checkbox: "تایید شده",
      startdate: "1401-10-12",
      actions: ["delete", "edit", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۴",
      lastname: "امنیت ۴",
      gender: "زن",
      itemType: "نوع ۴",
      group: "گروه ۴",
      checkbox: "تایید شده",
      startdate: "1401-10-14",
      actions: ["edit", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۵",
      lastname: "امنیت ۵",
      gender: "مرد",
      itemType: "نوع ۶",
      group: "گروه ۶",
      checkbox: "تایید شده",
      startdate: "1401-10-15",
      actions: ["delete", "edit", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۶",
      lastname: "امنیت ۶",
      gender: "زن",
      itemType: "نوع ۱",
      group: "گروه ۶",
      checkbox: "تایید شده",
      startdate: "1401-10-16",
      actions: ["edit", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۶",
      lastname: "امنیت ۷",
      gender: "مرد",
      itemType: "نوع ۶",
      group: "گروه ۶",
      checkbox: "تایید شده",
      startdate: "1401-10-17",
      actions: ["delete", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۷",
      lastname: "امنیت ۷",
      gender: "زن",
      itemType: "نوع ۷",
      group: "گروه ۷",
      checkbox: "تایید شده",
      startdate: "1401-10-18",
      actions: ["delete", "edit", "view"],
    },
    {
      id: nanoid(),
      name: "امنیت ۸",
      lastname: "امنیت ۸",
      gender: "مرد",
      itemType: "نوع ۸",
      group: "گروه ۸",
      checkbox: "تایید شده",
      startdate: "1401-10-19",
      actions: ["delete", "edit", "view"],
    },
  ],
};
